apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  DB_USERNAME: "coworking"
  DB_NAME: "coworking"
  DB_HOST: db-service
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  DB_PASSWORD: MTIzNDU2